name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cypress
      run: npm install cypress --save-dev
    - name: Run all tests
      run: npx cypress run

